### PR TITLE
ask for permission when needed

### PR DESCRIPTION
**Pull request by szotp**
I think it's bad idea to ask for permission at the start. For this reason I moved it to actual method call. Two things though:

1. I'm not sure what is the purpose of REQUEST_INSTALL_PACKAGES, do we need it?
2. openFile method will need to be called twice - once to get permission, and once again to open the file.

### CODE REVIEW

**Comment by crazecoder** [comment]
u will need it when open apk in Android

**Comment by lordgreg** [comment]
Hi. Wouldn't it be wise that the plugin would also has another method called `requestPermissions()` which we would always have to ask for and then just use plugin as previously? so we don't call the same function twice in a row?

At least this is how cordova plugins work.

**Comment by szotp** [comment]
@crazecoder so it's only required for case "apk", correct?

@lordgreg yes that would be ideal. I'm not sure how to implement the callback. `requestPermissions()` would need to wait until user selects the option

**Comment by crazecoder** [comment]
u can try it, I think it is later when request permission in apk case
if all is fine, i will  merge it

**Comment by crazecoder** [comment]
u can try it, I think it is later when request permission in apk case
if all is fine, i will  merge it

**Comment by szotp** [comment]
I updated the PR so that it waits for user decision. There is no `requestPermissions()` because it depends on file type which permissions will be requested.

**Pull request merged**
