### PR TITLE
AGP 8 namespace issue fix

### PR DESCRIPTION
**Pull request by prataptej**
fix: added namespace property to make compatible with gradle 8.0

### CODE REVIEW

**Comment by MrCyjaneK** [comment]
duplicate of #272 

is `buildToolsVersion '30.0.2'` needed?

**Comment by prataptej** [comment]
That was added by editor. It was not required so removed it. Please merge as I have dependency of this plugin in my project.

**Review by 0niel — APPROVED** [review]

**Comment by realDiegoR** [comment]
These changes were approved. Is this going to be merged?

**Comment by Megatronicus** [comment]
Launching lib\main.dart on sdk gphone64 x86 64 in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':open_file'.
> Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
   > Namespace not specified. Specify a namespace in the module's build file. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.

     If you've specified the package attribute in the source AndroidManifest.xml, you can use the AGP Upgrade Assistant to migrate to the namespace value in the build file. Refer to https://d.android.com/r/tools/upgrade-assistant/agp-upgrade-assistant for general information about using the AGP Upgrade Assistant.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 6s
Error: Gradle task assembleDebug failed with exit code 1

**Comment by Halim-Elmenshawi** [comment]
when will this branch be merged?

**Comment by sirkalmi** [comment]
I miss it too

**Comment by quanganh050998** [comment]
when will this branch be merged?

**Pull request merged**
