### PR TITLE
Dependancy updated to support with other packages in flutter v3

### PR DESCRIPTION
**Pull request by princeteck**
```WORK DONE```
1. `FFi` updated to v2.
2. android migrated from `v1` to `v2`, 
3. folder name corrected, ` plaform -> platform`.
4. package version updated to `3.2.2`
5. Gradle updated to `gradle-7.3.1`

### CODE REVIEW

**Comment by princeteck** [comment]
@crazecoder please check this PR and merge it so that it can be used with plugins using FFi version 2.0.1 and above.

**Comment by pranavo72bex** [comment]
LGTM 🚀

**Review by debojyoti452 — APPROVED** [review]
LGTM!

**Comment by lucas404x** [comment]
Any plan to merge this?

**Comment by tenraneko** [comment]
Can you merge this, please?

**Comment by princeteck** [comment]
> Can you merge this, please?

only if I had the Authority :P

**Comment by tenraneko** [comment]
> > Can you merge this, please?
> 
> only if I had the Authority :P

Last update open_file was 15 months ago 😢

Maybe you are publishing as your package (open_file2)?
Just provide a link to the author of open_file

**Comment by princeteck** [comment]
> > > Can you merge this, please?
> > 
> > 
> > only if I had the Authority :P
> 
> Last update open_file was 15 months ago 😢
> 
> Maybe you are publishing as your package (open_file2)? Just provide a link to the author of open_file

yes, Maybe that is what needs to be done. will wait for this week. if no response then will release it as a solo package with a back-link to this repo/package.

**Comment by bertoldofonseca** [comment]
Hi guys.
I was in a rush to get those updates, so I did another package forking this one.
You may want to check it out and give some comments. It's already published in `pub.dev`

https://github.com/bertoldofonseca/better_open_file
https://pub.dev/packages/better_open_file

I didn't spend much time naming it or thinking about new features. I just need to get it updated and usable from `pub.dev`

But I'm entirely open to receiving some feedback and helping to maintain and improve it (if needed)

**Comment by lucas404x** [comment]
> > > > Can you merge this, please?
> > > 
> > > 
> > > only if I had the Authority :P
> > 
> > 
> > Last update open_file was 15 months ago 😢
> > Maybe you are publishing as your package (open_file2)? Just provide a link to the author of open_file
> 
> yes, Maybe that is what needs to be done. will wait for this week. if no response then will release it as a solo package with a back-link to this repo/package.

Hello! Do you still think about publishing your version?

**Comment by AlexV525** [comment]
Discussed with the author offline and he'll be back to maintain soon.

**Pull request merged**
