### PR TITLE
fix opening filenames with spaces on linux

### LINKED ISSUE #126: linux: opening filenames with spaces fails
it seems filenames with spaces fail to open. 
It seems to be an escaping issue, i'm creating a PR

### PR DESCRIPTION
**Pull request by mx1up**
fixes #126 

I'm not sure about the other platforms, so I stayed out of it..

### CODE REVIEW

**Comment by miDeb** [comment]
Noticed this problem as well, but this is not actually enough since filenames can contain quotes as well! I solved this by appending a backslash in front of every character. (I wrote this in an email to the mantainer because I figured this might be a security vulnerability. It most likely isn't)

**Comment by miDeb** [comment]
I believe the best way to implement this is is to open the right process right away instead of using the `system` command: `Process.start("$linuxDesktopName-open", [filePath])`. That's how [this rust crate](https://github.com/Byron/open-rs/blob/c3d826220e59040d6d08d707ac771ba817165a07/src/lib.rs#L61) works as well.

**Comment by mx1up** [comment]
@miDeb you have a good point. TBH, I also don't understand why the system call is used here. I assumed the author had good reasons.. but maybe not as good as I hope ;) maybe @crazecoder can chime in.

I'll update my PR anyway to use Process

**Comment by miDeb** [comment]
The same issue seems to exist on macOS fwiw.

**Pull request merged**
